# Generated by Django 2.2.3 on 2019-07-24 23:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filepost',
            name='expiry_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filepost',
            name='link',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
